- name: Create MySQL Deployment
  kubernetes.core.k8s:
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: mysql
        namespace: "{{ namespace }}"
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: mysql
        template:
          metadata:
            labels:
              app: mysql
          spec:
            containers:
              - name: mysql
                image: mysql:8.0
                env:
                  - name: MYSQL_ROOT_PASSWORD
                    value: "{{ mysql_password }}"
                  - name: MYSQL_DATABASE
                    value: "{{ mysql_database }}"
                  - name: MYSQL_USER
                    value: "{{ mysql_user }}"
                  - name: MYSQL_PASSWORD
                    value: "{{ mysql_password }}"
                ports:
                  - containerPort: 3306
                volumeMounts:
                  - name: mysql-storage
                    mountPath: /var/lib/mysql
            volumes:
              - name: mysql-storage
                persistentVolumeClaim:
                  claimName: mysql-pvc
    kubeconfig: "{{ kubeconfig }}"
